config:
  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region ${region}
        log_group_name ${log_group_name}
        log_stream_prefix from-fluent-bit-
        auto_create_group ${auto_create_group}
        log_retention_days ${log_retention_days}
